name: dataframe_sql
channels:
  - conda-forge
dependencies:
  # required
  - pandas>=1.0.1

  # code checks
  - black=19.10b0
  - flake8
  - flake8-comprehensions>=3.1.0  # used by flake8, linting of unnecessary comprehensions
  - isort  # check that imports are in the right order
  - mypy=0.761
  - pycodestyle  # used by flake8

  # testing
  - freezegun
  - pytest>=5.0.1
  - pytest-xdist>=1.21

  - pip
  - pip:
      - black
      - sql-to-ibis==0.4.0

